### ISSUE TITLE
MSW not intercepting tRPC requests during testing (Jest + RTL)

### ISSUE THREAD

**Issue by swport** [t3-oss/create-t3-app#1592]
### Provide environment information

```
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 69.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 19.8.1 - ~/.nvm/versions/node/v19.8.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v19.8.1/bin/npm
    pnpm: 8.8.0 - /usr/local/bin/pnpm
```

### Describe the bug

I'm trying to unit test react components in my t3 app which are using tRPC apis like this - `api.send_otp.useMutation()`.

Since `api` is not available without trpc provider context, I've created a createTRPCReact wrapper to wrap my components for testing.

This is what the wrapper looks like:

```typescript
export const Trpc = createTRPCReact<AppRouter>();

const url = `http://localhost:${process.env.PORT ?? 3000}/api/trpc`;

const trpcClient = Trpc.createClient({
	transformer: superjson,
	links: [
		httpBatchLink({
			url,
		}),
	],
});

export const queryClient = new QueryClient({
	defaultOptions: { queries: { staleTime: Infinity } },
});

export const Wrapper = ({ children }: { children: ReactNode }) => {
	return (
		<Trpc.Provider client={trpcClient} queryClient={queryClient}>
			<QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
		</Trpc.Provider>
	);
};
```

This is my simple react component:

```typescript
// Component to test::
const NewComponent = () => {
	const otpMutation = api.send_otp.useMutation();

	const onclick = () => {
		otpMutation.mutate({ username: "hello@yahoo.com" });
	};

	return (
		<button data-testid="mutate-button" type="button" onClick={() => onclick()}>
			click
		</button>
	);
};
```

Test case:

```typescript
// Test case:
it("testing man", async () => {
	const { getByTestId } = render(<NewComponent />);
	const button = getByTestId("mutate-button");
	await waitFor(() => {
		fireEvent.click(button);
	});
});
```

And finally, this is what my jest setup looks like:

```javascript
import "@testing-library/jest-dom";

import { rest } from "msw";
import { setupServer } from "msw/node";

import fetch, { Request, Response, Headers } from "cross-fetch";

global.fetch = fetch;
global.Request = Request;
global.Response = Response;
global.Headers = Headers;

const handlers = [
	rest.all("*", () => {
		console.log("request coming");  // <--- this should be logged but not working
	}),
];

const server = setupServer(...handlers);

server.events.on("request:start", () => {
	console.log("request came"); // <--- this should be logged but not working
});

beforeAll(() => server.listen());

// Reset any request handlers that we may add during the tests,
// so they don't affect other tests.
afterEach(() => server.resetHandlers());

// Clean up after the tests are finished.
afterAll(() => server.close());
```

Mutation calls are not being intercepted, msw is working fine because I tried my test case with both a fetch call as well as directly using useMutation from react-query lib. It's just when I use tRPC api object, it doesn't work.

I feel I need to mock the `api` object but I'm simply not able to figure out how.

Please DO NOT close this issue without leaving a comment. Been stuck on this since yesterday and desperately looking to resolve this. I did raise this up as a question on discord server, received no response.

### Reproduction repo

NA

### To reproduce

NA

### Additional information

I tried testing using the way mentioned in the official doc - https://github.com/t3-oss/create-t3-app/blob/313a43bda7ab24eb7e3d0531e121f540297d8479/www/src/pages/en/usage/trpc.md?plain=1#L304

```typescript
const ctx = await createInnerTRPCContext({ session: null });
const caller = appRouter.createCaller(ctx);
```

However I'm not able to understand how do I use this for my use case. Plus, when I ran my test with those two lines, it threw this error:

```
Jest failed to parse a file....

   Details:

    /Users/sumit.wadhwa/Projects/training/wsp-main/node_modules/jose/dist/browser/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export { compactDecrypt } from './jwe/compact/decrypt.js';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (node_modules/openid-client/lib/client.js:11:14)
      at Object.<anonymous> (node_modules/openid-client/lib/issuer.js:8:19)
      at Object.<anonymous> (node_modules/openid-client/lib/index.js:1:118)
      at Object.<anonymous> (node_modules/next-auth/core/lib/oauth/callback.js:7:21)
      at Object.<anonymous> (node_modules/next-auth/core/routes/callback.js:8:40)
      at Object.<anonymous> (node_modules/next-auth/core/routes/index.js:37:40)
      at Object.<anonymous> (node_modules/next-auth/core/index.js:10:38)
      at Object.<anonymous> (node_modules/next-auth/next/index.js:9:13)
      at Object.<anonymous> (node_modules/next-auth/index.js:25:37)
      at Object.<anonymous> (src/server/authentication/auth.ts:580:26)
      at Object.<anonymous> (src/server/api/trpc.ts:1320:28)
      at Object.<anonymous> (src/components/Auth/Otp/tests/LoginForm.test.tsx:13:15)
```

**Comment by c-ehrlich** [comment]
here's an example with unit tests that use mocked tRPC endpoints https://github.com/c-ehrlich/msw-trpc-example

**Comment by swport** [comment]
i suck.
