### ISSUE TITLE
bug: TRPCClientError: Dynamic server usage: Page couldn't be rendered statically because it used `headers`

### ISSUE THREAD

**Issue by dBianchii** [t3-oss/create-t3-app#1604]
### Provide environment information

CT3A Selected Options to bootstrap the app:
- TRPC,
- Prisma,
- Next.Auth
- Tailwind
- Experimental AppDir option

```
  System:
    OS: Windows 10 10.0.23565
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
    Memory: 5.45 GB / 15.82 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Local\pnpm\pnpm.EXE
```
"ct3aMetadata": {
    "initVersion": "7.22.0"
  },

### Describe the bug

When building my app with pnpm build, I get this error:

```
TRPCClientError: Dynamic server usage: Page couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
      at TRPCClientError.from (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\439.js:1:23528)
      at D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\439.js:1:27934
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at runNextTicks (node:internal/process/task_queues:64:3)
      at listOnTimeout (node:internal/timers:538:9)
      at process.processTimers (node:internal/timers:512:7) {
    meta: undefined,
    shape: undefined,
    data: undefined,
    [cause]: DynamicServerError: Dynamic server usage: Page couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
        at staticGenerationBailout (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\686.js:1:3919)
        at headers (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\686.js:1:1139)
        at Object.headers (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\app\page.js:1:3706)
        at Object.headers (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\439.js:5:5214)
        at fetchHTTPResponse (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\439.js:1:24909)
        at streamingJsonHttpRequester (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\439.js:5:4374)
        at Object.fetch (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\439.js:5:5083)
        at Timeout.dispatch (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\439.js:1:26543)
        at listOnTimeout (node:internal/timers:569:17)
        at process.processTimers (node:internal/timers:512:7) {
      digest: 'DYNAMIC_SERVER_USAGE'
    }
  },
  elapsedMs: 5
}
 << query  #2 post.hello  {
  input: { text: 'from tRPC' },
  result: TRPCClientError: Dynamic server usage: Page couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
      at TRPCClientError.from (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\439.js:1:23528)
      at D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\439.js:1:27934
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at runNextTicks (node:internal/process/task_queues:64:3)
      at listOnTimeout (node:internal/timers:538:9)
      at process.processTimers (node:internal/timers:512:7) {
    meta: undefined,
    shape: undefined,
    data: undefined,
    [cause]: DynamicServerError: Dynamic server usage: Page couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
        at staticGenerationBailout (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\686.js:1:3919)
        at headers (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\686.js:1:1139)
        at Object.headers (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\app\page.js:1:3706)
        at Object.headers (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\439.js:5:5214)
        at fetchHTTPResponse (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\439.js:1:24909)
        at streamingJsonHttpRequester (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\439.js:5:4374)
        at Object.fetch (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\439.js:5:5083)
        at Timeout.dispatch (D:\Users\gdbia\Documents\Github\t3-app-delete\.next\server\chunks\439.js:1:26543)
        at listOnTimeout (node:internal/timers:569:17)
        at process.processTimers (node:internal/timers:512:7) {
      digest: 'DYNAMIC_SERVER_USAGE'
    }
  },
  elapsedMs: 16
}
```

### Reproduction repo

No need. Just initiate a new project using app dir and run build script

### To reproduce

Just scaffhold a new app using App Dir option, and then create a new build

### Additional information

![image](https://github.com/t3-oss/create-t3-app/assets/17372417/e28812cb-24b9-46f3-90ce-1eb8300bb930)

**Comment by dBianchii** [comment]
Hi, I just realized this a duplicate of https://github.com/t3-oss/create-t3-app/issues/1599
