### ISSUE TITLE
bug: Cannot access 'routeName' before initialization

### ISSUE THREAD

**Issue by ahkhanjani** [t3-oss/create-t3-app#1631]
### Provide environment information

 System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 10.21 GB / 19.84 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.5.0 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.0 - C:\Program Files\nodejs\pnpm.CMD

### Describe the bug

I recently changed the structure of my routers from being flat (root -> router -> procedure) to nested (root -> (variable depth routers) -> procedure) and while it works perfectly fine for any other router, one of my routers throws this error:

```
ReferenceError: Cannot access 'exampleRouter' before initialization
    at Module.exampleRouter(webpack-internal:///(api)/./src/server/api/routers/live/quiz/multi-choice.ts:4:59)
    at eval (webpack-internal:///(api)/./src/server/api/routers/live/quiz/index.ts:33:61)
    at (api)/./src/server/api/routers/live/quiz/index.ts (xxx\.next\server\pages\api\trpc\[trpc].js:382:1)
    at __webpack_require__ (xxx\.next\server\webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./src/server/api/routers/live/quiz/multi-choice.ts:17:59)
    at (api)/./src/server/api/routers/live/quiz/multi-choice.ts (xxx\.next\server\pages\api\trpc\[trpc].js:402:1)
    at __webpack_require__ (xxx\.next\server\webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./src/server/api/routers/live/state.ts:17:76)
    at (api)/./src/server/api/routers/live/state.ts (xxx\.next\server\pages\api\trpc\[trpc].js:412:1)
    at __webpack_require__ (xxx\.next\server\webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./src/server/api/routers/live/index.ts:7:64)
    at (api)/./src/server/api/routers/live/index.ts (xxx\.next\server\pages\api\trpc\[trpc].js:352:1)
    at __webpack_require__ (xxx\.next\server\webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./src/server/api/root.ts:9:82)
    at (api)/./src/server/api/root.ts (xxx\.next\server\pages\api\trpc\[trpc].js:332:1)
```

I tried to debug or log my root router to see the value of that one router at runtime. Debugger didn't work so I wrote a `console.log` of my root router in my next-auth sign in callback so that it can run on the server. And to my surprise, the `console.log` made it work again. So for some reason, that router is not initialized automatically and my `console.log` makes it initialize.

This can just be me doing something stupid, so I'll create a repo soon. Another thing is that, I have another almost identical router right next to it and it works. I tried to change their order in different combinations and it doesn't make a difference.

I'm sorry for my vague description without an example. For now I'm just wondering if there is any known bugs that could possibly cause this. I would also appreciate an example repo of a deeply nested router, as it's missing in the documentation.

### Reproduction repo

will add soon

### To reproduce

Not sure yet

### Additional information

Nextjs 13.5.6

**Comment by ahkhanjani** [comment]
This was a tRPC bug. I accidentally opened it here. Moved to [here](https://github.com/trpc/trpc/issues/4971).
