### ISSUE TITLE
feat: Data Seeding CLI for Drizzle

### ISSUE THREAD

**Issue by mikah13** [t3-oss/create-t3-app#1679]
### Is your feature request related to a problem? Please describe.

I was looking for an elegant solution to add seeding data in Drizzle via a CLI command. There doesn't seem to be an answer from the documentation, so I went ahead and gave it a try. This is what I came up with so far

### Describe the solution you'd like to see

additional script for data seeding purpose in the package.json

````diff
"script": {
    "build": "next build",
    "db:push": "dotenv drizzle-kit push:MySQL",
    "db:studio": "dotenv drizzle-kit studio",
+   "db:seed": "dotenv npx tsx ./src/server/db/seed.ts",
    "dev": "next dev",
    "lint": "next lint",
    "start": "next start",
}

````

  
  with a default seed.ts file, defined in `./src/server/db/seed.ts`
  
  ```ts
  
  import { db } from ".";
import { posts } from "./schema";

const firstPost = await db.insert(posts).values({
      name: "My first blog post",
});
```

### Describe alternate solutions

N/A

**Comment by juliusmarminge** [comment]
Feel free to add this to the documentatin!

**Comment by Nitinshukla88** [comment]
I would like to work on it.Please assign this issue to me @juliusmarminge

**Comment by juliusmarminge** [comment]
We don't assign issues, just start working on it

**Comment by Nitinshukla88** [comment]
Ok got it.

**Comment by f0r3n51c6uy** [comment]
Today, I also searched a while for an elegant and working solution. I adapted your proposed solution so that it will work for my SvelteKit application.

Assume the following project structure:
```
.
├── README.md
├── drizzle
│   ├── ...
├── drizzle.config.ts
├── package-lock.json
├── package.json
├── postcss.config.js
├── src
│   ├── app.d.ts
│   ├── app.html
│   ├── hooks.server.ts
│   ├── lib
│   │   ├── index.ts
│   │   ├── server
│   │   │   ├── database
│   │   │   │   ├── db.ts
│   │   │   │   ├── schema.ts
│   │   │   │   └── seed.ts
│   └── routes
│       ├── ...
├── svelte.config.js
├── svelte.config.ts
├── tailwind.config.js
├── tsconfig.json
└── vite.config.ts
```
The file `db.ts` contains the database connector used in the SvelteKit application. Since it use the SvelteKit way to access environment variables (e.g. `import { DB_HOST } from "$env/static/private"`) it cannot easily imported in `seed.ts` and executed using `tsc`. Attempts will fail with the following error code:
 ```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '$env' imported from  src/lib/server/database/db.ts
```
 Therefore,  the database driver needed to be created in `seed.ts` again.

```typescript
import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import { users } from "./schema";

const main = async () => {

const connection = await mysql.createConnection({
        host: process.env.DB_HOST,
        port: Number(process.env.DB_PORT) || 3306,
        user: process.env.DB_USERNAME,
        password: process.env.DB_PASSWORD,
        database: process.env.DB_NAME,
    });
    
    const db = drizzle(connection);
    await db.insert(users).values([
        {name: "Test",  id:  1}
   ]);
};

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        console.log("Seeding done!");
        process.exit(0);
    });
```
The package.json looks similar to the solution proposed by @mikah13 but the `.env` file containing environment variables is specified in addition.

```json
"scripts": {
     "drizzle:seed": "npx tsx --env-file=./.env ./src/lib/server/database/seed.ts"
```
I hope that this will help any developer using SvelteKit to save some time. 😄

**Comment by hunterwilhelm** [comment]
I'm getting this error with `npx tsx ./src/server/db/seed.ts`


    "mysql2": "^3.11.3",

```
/node_modules/src/mysql2/driver.ts:108
        return typeof client.promise === 'function';
                             ^


TypeError: Cannot read properties of undefined (reading 'promise')
    at isCallbackClient (/node_modules/src/mysql2/driver.ts:108:23)
    at construct (/node_modules/src/mysql2/driver.ts:71:28)
    at drizzle (/node_modules/src/mysql2/driver.ts:165:9)
    at <anonymous> (/src/server/db/seed.ts:6:12)
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```
I don't have time to investigate rn, I'll check back later.
