### ISSUE TITLE
bug: unable to run db:push script due to drizzle-kit bug in 0.20.7

### ISSUE THREAD

**Issue by jenewland1999** [t3-oss/create-t3-app#1705]
### Provide environment information

  System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 405.33 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/Library/Caches/fnm_multishells/50100_1703521770493/bin/node
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/50100_1703521770493/bin/npm
    pnpm: 8.12.1 - ~/Library/pnpm/pnpm
    bun: 1.0.20 - ~/.bun/bin/bun

### Describe the bug

Scaffolding a create-t3-app with Drizzle as the ORM of choice, and subsequently trying to run `bun run db:push` (tried pnpm too) will result in the following error message:

```text
node:internal/modules/cjs/loader:573
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './relations' is not defined by "exports" in /Users/jenewland1999/dev/jenewland1999/test-t3/node_modules/drizzle-orm/package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:359:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:695:9)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at src/introspect-pg.ts (/Users/jenewland1999/dev/jenewland1999/test-t3/node_modules/.pnpm/drizzle-kit@0.20.8/node_modules/drizzle-kit/bin.cjs:18942:24) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.17.1
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction repo

https://github.com/jenewland1999/t3-bug-demo

### To reproduce

1. Run `bunx create-t3-app@latest --trpc --drizzle --tailwind --nextAuth --appRouter t3-app`
2. Populate the `.env` file with the relevant values
3. Run `bun run db:push`
4. Witness error message
5. Cry
6. Report bug <--- we're at this stage now

### Additional information

Fix available for issue by upgrading drizzle-orm 0.29.2 and drizzle-kit to 0.20.8. Also, as of drizzle-kit 0.20.0, `dotenv` is no longer required because Drizzle now loads env vars automatically [source](https://github.com/drizzle-team/drizzle-kit-mirror/releases/tag/v0.20.0).

**Comment by salman-ar-sar** [comment]
Can confirm this bug is present.

**Comment by linardsblk** [comment]
I removed dotenv-cli dependency, removed it from package.json scripts and upgraded drizzle-orm and drizzle-kit just like in #1707 to my fresh T3 project and I still have the same error when running `bun run db:push`

```
node:internal/modules/cjs/loader:499
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './relations' is not defined by "exports" in /Users/linards/Documents/projects/atlaides/node_modules/drizzle-orm/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:464:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:748:3)
    at resolveExports (node:internal/modules/cjs/loader:493:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:533:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at src/introspect-pg.ts (/Users/linards/Documents/projects/atlaides/node_modules/drizzle-kit/bin.cjs:18794:24) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

```


Should I wait for a release or can someone try to reproduce in pre-release version?

**Comment by F4lseDev** [comment]
I think I have a partial result. The latest version does not work, but version 0.19.13 for Drizzle Kit does:

drizzle-kit@0.19.13

Now, you need to change the 'URI' to 'connectionString' in the Drizzle config.

If you encounter the error "❌ Invalid environment variables:" when trying to start Drizzle Studio, you need to add the URI directly into the config. I read that Drizzle doesn't work properly with the traditional '.env' files.

I hope its get fixed

**Comment by LukaHietala** [comment]
I also have the same problem :(

**Comment by austin-karren** [comment]
I can confirm that this is still an issue with create-t3-app. Upgrading the packages fixed the issue so why is this still a problem?
