### ISSUE TITLE
bug: Calling a tRPC endpoint from a server component gives `connect ECONNREFUSED 127.0.0.1:3000` in prod (vercel and docker) but works fine in dev.

### ISSUE THREAD

**Issue by Meriegg** [t3-oss/create-t3-app#1737]
### Provide environment information

 System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
    Memory: 2.05 GB / 3.75 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.14.1 - ~/.nvm/versions/node/v20.11.0/bin/pnpm

(This is WSL2 information, my main OS is Windows 10)

### Describe the bug

I have an endpoint called `getCurrentSession`. I am mainly using this endpoint to verify if the user is logged in or not by calling it on the server and catching any error it throws. In development this works just fine, but in production (both Vercel and Docker running locally) It throws the following error:

```
[TRPCClientError]: request to http://localhost:3000/api/trpc/account.getCurrentSession?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D failed, reason: connect ECONNREFUSED 127.0.0.1:3000
    at u.from (/app/.next/server/chunks/9938.js:1:2567)
    at /app/.next/server/chunks/9938.js:1:6400
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  meta: undefined,
  shape: undefined,
  data: undefined,
  [cause]: h [FetchError]: request to http://localhost:3000/api/trpc/account.getCurrentSession?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D failed, reason: connect ECONNREFUSED 127.0.0.1:3000
      at ClientRequest.<anonymous> (/app/.next/server/chunks/9938.js:5:20148)
      at ClientRequest.emit (node:events:518:28)
      at Socket.socketErrorListener (node:_http_client:495:9)
      at Socket.emit (node:events:518:28)
      at emitErrorNT (node:internal/streams/destroy:169:8)
      at emitErrorCloseNT (node:internal/streams/destroy:128:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    type: 'system',
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED'
  }
}
```

### Reproduction repo

https://github.com/Meriegg/hotello-demo

### To reproduce

Clone the reproduction repo, add the required environment variables, deploy to vercel or create a docker image following the instructions present at [https://create.t3.gg/en/deployment/docker](https://create.t3.gg/en/deployment/docker), sign up or log in.

### Additional information

The endpoint can be found at `src/server/api/routers/account.ts`.
The utility function I am using to verify auth state is found at `src/app/utils/get-page-session.ts`.
The routes I am using the utility are:
1. `src/app/account/dashboard/page.tsx`
2. `src/app/account/dashboard/bookings/page.tsx`
3. `src/app/admin/layout.tsx`

**Comment by Meriegg** [comment]
Update: I just did a little workaround for my `getCurrentSession` route and I found out that any tRPC route being called from an `async` react component on the server will throw that error (`src/app/account/dashboard/bookings/page.tsx` in the reproduction repo)
