### ISSUE TITLE
bug: first steps, discord login: [auth][cause]: WWWAuthenticateChallengeError: server responded with a challenge in the WWW-Authenticate HTTP Header

### ISSUE THREAD

**Issue by mindhaq** [t3-oss/create-t3-app#2020]
### Provide environment information

ct3aMetadata.initVersion: 7.38.1

  System:
    OS: macOS 14.7
    CPU: (12) arm64 Apple M2 Max
    Memory: 1.10 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.7.0 - ~/.nvm/versions/node/v22.7.0/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v22.7.0/bin/npm
    pnpm: 9.12.3 - /opt/homebrew/bin/pnpm
    Watchman: 2024.11.04.00 - /opt/homebrew/bin/watchman

### Describe the bug

After creating a new t3g app (my first ever) with TS, Prisma, tRPC, PostGres and creating and configuring a new discord app, after logging in via Discord oauth authorize screen, I get redirected to http://localhost:3000/api/auth/error?error=Configuration.

Stacktrace in console:

```
[auth][error] CallbackRouteError: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: WWWAuthenticateChallengeError: server responded with a challenge in the WWW-Authenticate HTTP Header
    at processGenericAccessTokenResponse (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/.next/server/chunks/node_modules__pnpm_dca423._.js:2256:15)
    at processAuthorizationCodeOAuth2Response (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/.next/server/chunks/node_modules__pnpm_dca423._.js:2527:26)
    at Module.processAuthorizationCodeResponse (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/.next/server/chunks/node_modules__pnpm_dca423._.js:2467:12)
    at handleOAuth (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/.next/server/chunks/c1962_@auth_core_82247d._.js:3333:243)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Module.callback (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/.next/server/chunks/c1962_@auth_core_82247d._.js:3782:41)
    at async AuthInternal (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/.next/server/chunks/c1962_@auth_core_82247d._.js:4859:24)
    at async Auth (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/.next/server/chunks/c1962_@auth_core_82247d._.js:5120:34)
    at async AppRouteRouteModule.do (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:33313)
    at async AppRouteRouteModule.handle (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:10:40382)
    at async doRender (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1455:42)
    at async responseGenerator (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1814:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1824:28)
    at async DevServer.renderPageComponent (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:2240:24)
    at async DevServer.renderToResponseImpl (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:2278:32)
    at async DevServer.pipeImpl (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:960:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:281:17)
    at async DevServer.handleRequestImpl (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:853:17)
    at async /Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:373:20
    at async Span.traceAsyncFn (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/trace/trace.js:153:20)
    at async DevServer.handleRequest (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:370:24)
    at async invokeRender (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:183:21)
    at async handleRequest (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:360:24)
    at async requestHandlerImpl (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:384:13)
    at async Server.requestListener (/Users/rue/code/practice/userdb/userdb-t3g-nextjs/node_modules/.pnpm/next@15.0.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/start-server.js:142:13)
[auth][details]: {
  "0": {
    "scheme": "basic",
    "parameters": {
      "error": "invalid_client",
      "error_description": ""
    }
  },
  "provider": "discord"
}
```

### Reproduction repo

-

### To reproduce

See description

### Additional information

Before, I forgot to configure the redirect in the discord app. Got an error stating that. After adding http://localhost:3000/api/auth/callback/discord as stated in the "[first steps](https://create.t3.gg/en/usage/first-steps#authentication)" docs, the bug as described happened.

**Comment by dijkie73** [comment]
Same here

**Comment by thathurtabit** [comment]
I'm getting this too, but should this be reported to [NextAuth](https://github.com/nextauthjs/next-auth) or maybe Discord.

This could be related: https://github.com/discord/discord-api-docs/issues/7311

**Comment by Murderlon** [comment]
Were one of you able to solve it?

**Comment by nikolasstow** [comment]
I had the same issue and discovered I had put the incorrect Client Secret in my .env. I can't say this will fix your issue, but it fixed mine.

**Comment by ryota-murakami** [comment]
same here

**Comment by chenxi2015** [comment]
I solved it by modifying the AUTH_DISCORD_SECRET for Discord. Note: It's not the Public Key value, but the Client Secret value in OAuth2.
