### ISSUE TITLE
add `min(1)` on schema and reference to the docs for `NEXTAUTH_SECRET` on `.env.example`

### ISSUE THREAD

**Issue by hnqg** [t3-oss/create-t3-app#304]
## Is your feature request related to a problem? Please describe.
Some users are not too familiar with `Next-Auth` to know that the `NEXTAUTH_SECRET` needs to be a valid string. Unfortunately, the error logs on the terminal are not so clear.

```
[next-auth][error][SIGNIN_OAUTH_ERROR]
https://next-auth.js.org/errors#signin_oauth_error "ikm" must be at least one byte in length {
  error: {
    message: '"ikm" must be at least one byte in length',
    stack: 'TypeError: "ikm" must be at least one byte in length\n' +
      '    at normalizeIkm (/mnt/repos/website/testing/node_modules/@panva/hkdf/dist/node/cjs/index.js:26:15)\n' +
      '    at hkdf (/mnt/repos/website/testing/node_modules/@panva/hkdf/dist/node/cjs/index.js:47:60)\n' +
      '    at getDerivedEncryptionKey (/mnt/repos/website/testing/node_modules/next-auth/jwt/index.js:114:34)\n' +
      '    at Object.encode (/mnt/repos/website/testing/node_modules/next-auth/jwt/index.js:48:34)\n' +
      '    at createState (/mnt/repos/website/testing/node_modules/next-auth/core/lib/oauth/state-handler.js:29:34)\n' +
      '    at getAuthorizationUrl (/mnt/repos/website/testing/node_modules/next-auth/core/lib/oauth/authorization-url.js:68:53)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at async Object.signin (/mnt/repos/website/testing/node_modules/next-auth/core/routes/signin.js:37:24)\n' +
      '    at async NextAuthHandler (/mnt/repos/website/testing/node_modules/next-auth/core/index.js:238:26)\n' +
      '    at async NextAuthNextHandler (/mnt/repos/website/testing/node_modules/next-auth/next/index.js:23:19)',
    name: 'TypeError'
  },
  providerId: 'github',
  message: '"ikm" must be at least one byte in length'
}
```

## Describe the solution you'd like
- Add some reference link in the .env.example pointing to the `NEXTAUTH_SECRET` docs in the `Next Auth` documentation.
- Add `.min(1)` in the .env schema on the `NEXTAUTH_SECRET` variable, to make the error log more clear.

**Comment by juliusmarminge** [comment]
Not sure why you are getting this error.

In dev, NextAuth will automatically hash your options in order to generate a secret.

In prod, NextAuth will throw an error if the NEXT_AUTH_SECRET is not set.

Link to relevant docs: https://next-auth.js.org/configuration/options#secret

**Comment by hnqg** [comment]
since i didn't see anyone else complaining about this, i'm closing the issue
