### ISSUE TITLE
bug: `example.hello` query fails once on page load (according to logger, tRPC v9/dev only)

### ISSUE THREAD

**Issue by c-ehrlich** [t3-oss/create-t3-app#390]
### Provide environment information

ct3a version 5.9.0
```
 System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 171.02 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/Documents/dev/node_modules/.bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
```

### Describe the bug

Several people on Discord have posted about this bug, and I can confirm that I can reproduce it.

After scaffolding a new t3 app with all options selected, and opening the app in localhost, on every page reload the `example.hello` query fails once before succeeding, according to the logger. 

Here is the stack trace of the error:
```
TRPCClientError: The operation was aborted.
    at Function.from (webpack-internal:///./node_modules/@trpc/client/dist/TRPCClientError-09b8a26b.esm.js:78:14)
    at eval (webpack-internal:///./node_modules/@trpc/client/links/httpBatchLink/dist/trpc-client-links-httpBatchLink.esm.js:209:87)
    at Object.onDone (webpack-internal:///./node_modules/@trpc/client/dist/trpc-client.esm.js:196:13)
    at Object.done (webpack-internal:///./node_modules/@trpc/client/dist/trpc-client.esm.js:110:219)
    at promise.cancel (webpack-internal:///./node_modules/@trpc/client/dist/trpc-client.esm.js:325:17)
    at cancelFn (webpack-internal:///./node_modules/react-query/es/core/retryer.js:118:28)
    at Retryer.cancel (webpack-internal:///./node_modules/react-query/es/core/retryer.js:41:40)
    at Query.removeObserver (webpack-internal:///./node_modules/react-query/es/core/query.js:209:26)
    at QueryObserver.destroy (webpack-internal:///./node_modules/react-query/es/core/queryObserver.js:76:23)
    at QueryObserver.onUnsubscribe (webpack-internal:///./node_modules/react-query/es/core/queryObserver.js:61:12)
    at eval (webpack-internal:///./node_modules/react-query/es/core/subscribable.js:26:13)
    at eval (webpack-internal:///./node_modules/react-query/es/react/useBaseQuery.js:82:7)
    at safelyCallDestroy (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22927:5)
    at commitHookEffectListUnmount (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23095:11)
    at invokePassiveEffectUnmountInDEV (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:25202:13)
    at invokeEffectsInDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27346:11)
    at commitDoubleInvokeEffectsInDEV (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27319:7)
    at flushPassiveEffectsImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27051:5)
    at flushPassiveEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26979:14)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26764:9)
    at workLoop (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:266:34)
    at flushWork (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:533:21)
```

See below for more details and some theories.

### To reproduce

- `npx create-t3-app@latest`, install all options
- start the dev server and look in the terminal

### Additional information

- It happens in `@latest` in dev, but not in prod.
- It doesn't happen at all in `@next`.
- `useQuery`'s `onError` isn't run.
- It seems like the first query isn't being sent at all - despite one failure and one success being logged, only one request to `http://localhost:3000/api/trpc/example.hello` is being made, and the route is only run once in the server (see screenshot below)
- I placed a bunch of console logs in the server, here are some screenshots:

<img width="2559" alt="image" src="https://user-images.githubusercontent.com/8353666/188229032-e8a04760-59a3-423f-b3c7-8e9ff7af5e9f.png">

A couple of hypotheses:
- Maybe it's an issue with the logger?
- Maybe it's related to the component being mounted twice? 

There are no open issues that seem related to this in the tRPC repo - could be one of two things:
1. specific to our setup
2. nobody else is noticing it because it has no perceived impact outside of the logger

**Comment by AlvaroAquijeDiaz** [comment]
upvoting this

**Comment by SeanCassiere** [comment]
Got the same error.

These were the steps taken:

- Init project using `npx create-t3-app@latest`.
```json
{
	"ct3aMetadata": {
		"initVersion": "5.9.0"
	}
}
```
- During project init, all options were selected. (Prisma, NextAuth, Tailwind, tRPC)
- Post init, commented out the NextAuth plugin and env checking for **Discord OAuth**.

Upon boot up (`npm run dev`), the following error is shown.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/33615041/188255733-56a83902-ad22-4eb0-a79e-9109e5758c17.png">

This is as much as I could extract from the error object in JSON.
```json
{
        "elapsedMs": 3,
        "context": {},
	"input": {
		"text": "from tRPC"
	},
	"result": {
		"originalError": {
			"name": "TRPCAbortError"
		},
		"isDone": true,
		"name": "TRPCClientError"
	}
}
```

And this is the stack trace being provided in the error.
```
TRPCAbortError: The operation was aborted.\n    at eval (webpack-internal:///./node_modules/@trpc/client/links/httpBatchLink/dist/trpc-client-links-httpBatchLink.esm.js:209:92)\n    at Object.onDone (webpack-internal:///./node_modules/@trpc/client/dist/trpc-client.esm.js:196:13)\n    at Object.done (webpack-internal:///./node_modules/@trpc/client/dist/trpc-client.esm.js:110:219)\n    at promise.cancel (webpack-internal:///./node_modules/@trpc/client/dist/trpc-client.esm.js:325:17)\n    at cancelFn (webpack-internal:///./node_modules/react-query/es/core/retryer.js:118:28)\n    at Retryer.cancel (webpack-internal:///./node_modules/react-query/es/core/retryer.js:41:40)\n    at Query.removeObserver (webpack-internal:///./node_modules/react-query/es/core/query.js:209:26)\n    at QueryObserver.destroy (webpack-internal:///./node_modules/react-query/es/core/queryObserver.js:76:23)\n    at QueryObserver.onUnsubscribe (webpack-internal:///./node_modules/react-query/es/core/queryObserver.js:61:12)\n    at eval (webpack-internal:///./node_modules/react-query/es/core/subscribable.js:26:13)\n    at eval (webpack-internal:///./node_modules/react-query/es/react/useBaseQuery.js:82:7)\n    at safelyCallDestroy (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22927:5)\n    at commitHookEffectListUnmount (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23095:11)\n    at invokePassiveEffectUnmountInDEV (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:25202:13)\n    at invokeEffectsInDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27346:11)\n    at commitDoubleInvokeEffectsInDEV (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27319:7)\n    at flushPassiveEffectsImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27051:5)\n    at flushPassiveEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26979:14)\n    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26764:9)\n    at workLoop (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:266:34)\n    at flushWork (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:239:14)\n    at MessagePort.performWorkUntilDeadline (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:533:21)"
```

**Comment by KATT** [comment]
Seems like an issue with trpc, feel free to open it in our repo
