### ISSUE TITLE
bug: trpc install step has dependency resolution problems in node 16+ (using npm) 

### ISSUE THREAD

**Issue by jacksonopp** [t3-oss/create-t3-app#700]
### Provide environment information

  System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.53 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2021.11.15.00 - /usr/local/bin/watchman

### Describe the bug

When running the command `npm create t3-app`, the `trpc` install step is aborted due to dependency conflicts:

```
Installing packages...
✔ Successfully installed nextAuth
✔ Successfully installed prisma
✔ Successfully installed tailwind
⠙ Installing trpc...Aborting installation...
Error: Command failed: npm install  react-query@3.39.2 superjson @trpc/server @trpc/client @trpc/next @trpc/react
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: template@0.1.0
npm ERR! Found: @trpc/client@10.0.0-rc.6
npm ERR! node_modules/@trpc/client
npm ERR!   @trpc/client@"*" from the root project
npm ERR!   peer @trpc/client@"10.0.0-rc.6" from @trpc/next@10.0.0-rc.6
npm ERR!   node_modules/@trpc/next
npm ERR!     @trpc/next@"*" from the root project
npm ERR!   1 more (@trpc/react-query)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @trpc/react@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @trpc/client@9.27.4
npm ERR! node_modules/@trpc/client
npm ERR!   peer @trpc/client@"9.27.4" from @trpc/react@9.27.4
npm ERR!   node_modules/@trpc/react
npm ERR!     @trpc/react@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/jacksonoppenheim/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jacksonoppenheim/.npm/_logs/2022-11-06T17_52_59_336Z-debug-0.log
```

Found in node 16 and node 18

## With the auto-install

1. Use npm 16 or higher
2. Run the command `npm create t3-app`
3. Select *at least* `trpc` as a package to install
4. Select (Y) for do you want us to run `npm install`
5. Observe that the install step aborts

## Manually installing
1. Use npm 16 or higher
2. Run the command `npm create t3-app`
3. Select *at least* `trpc` as a package to install
4. Select (n) for do you want us to run `npm install`
5. `cd` in to your project
6. run `npm install`
7. Observe dependency resolution error

### Additional information

# Full error log file contents

```
0 verbose cli /Users/jacksonoppenheim/.nvm/versions/node/v16.15.1/bin/node /Users/jacksonoppenheim/.nvm/versions/node/v16.15.1/bin/npm
1 info using npm@8.11.0
2 info using node@v16.15.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/jacksonoppenheim/.nvm/versions/node/v16.15.1/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/Users/jacksonoppenheim/projects/surreal-todo/.npmrc Completed in 0ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/Users/jacksonoppenheim/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/Users/jacksonoppenheim/.nvm/versions/node/v16.15.1/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 11ms
19 timing npm:load:configload Completed in 11ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm install react-query@3.39.2 superjson @trpc/server @trpc/client @trpc/next @trpc/react
23 verbose argv "install" "react-query@3.39.2" "superjson" "@trpc/server" "@trpc/client" "@trpc/next" "@trpc/react"
24 timing npm:load:setTitle Completed in 15ms
25 timing config:load:flatten Completed in 2ms
26 timing npm:load:display Completed in 2ms
27 verbose logfile logs-max:10 dir:/Users/jacksonoppenheim/.npm/_logs
28 verbose logfile /Users/jacksonoppenheim/.npm/_logs/2022-11-06T17_52_59_336Z-debug-0.log
29 timing npm:load:logFile Completed in 4ms
30 timing npm:load:timers Completed in 1ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 34ms
33 timing arborist:ctor Completed in 0ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 153ms
37 timing idealTree:userRequests Completed in 3ms
38 silly idealTree buildDeps
39 silly fetch manifest react-query@3.39.2
40 timing arborist:ctor Completed in 0ms
41 http fetch GET 200 https://registry.npmjs.org/react-query 89ms (cache hit)
42 silly fetch manifest react@18.2.0
43 http fetch GET 200 https://registry.npmjs.org/react 6ms (cache hit)
44 silly fetch manifest superjson@*
45 http fetch GET 200 https://registry.npmjs.org/superjson 3ms (cache hit)
46 silly fetch manifest @trpc/server@*
47 http fetch GET 200 https://registry.npmjs.org/@trpc%2fserver 5ms (cache hit)
48 silly fetch manifest @trpc/client@*
49 http fetch GET 200 https://registry.npmjs.org/@trpc%2fclient 3ms (cache hit)
50 silly fetch manifest @trpc/next@*
51 http fetch GET 200 https://registry.npmjs.org/@trpc%2fnext 9ms (cache hit)
52 silly fetch manifest @tanstack/react-query@^4.3.8
53 http fetch GET 200 https://registry.npmjs.org/@tanstack%2freact-query 3ms (cache hit)
54 silly fetch manifest react-dom@18.2.0
55 http fetch GET 200 https://registry.npmjs.org/react-dom 6ms (cache hit)
56 silly fetch manifest react-native@*
57 http fetch GET 200 https://registry.npmjs.org/react-native 12ms (cache hit)
58 silly fetch manifest react@18.1.0
59 silly fetch manifest @trpc/react-query@^10.0.0-proxy-beta.21
60 http fetch GET 200 https://registry.npmjs.org/@trpc%2freact-query 8ms (cache hit)
61 silly fetch manifest next@12.3.1
62 http fetch GET 200 https://registry.npmjs.org/next 26ms (cache hit)
63 silly fetch manifest fibers@>= 3.1.0
64 http fetch GET 200 https://registry.npmjs.org/fibers 5ms (cache hit)
65 silly fetch manifest node-sass@^6.0.0 || ^7.0.0
66 http fetch GET 200 https://registry.npmjs.org/node-sass 3ms (cache hit)
67 silly fetch manifest sass@^1.3.0
68 http fetch GET 200 https://registry.npmjs.org/sass 2ms (cache hit)
69 silly fetch manifest @trpc/react@*
70 http fetch GET 200 https://registry.npmjs.org/@trpc%2freact 3ms (cache hit)
71 silly fetch manifest @trpc/client@9.27.4
72 silly fetch manifest @trpc/server@9.27.4
73 silly placeDep ROOT @trpc/client@10.0.0-rc.6 OK for: template@0.1.0 want: *
74 silly placeDep ROOT @trpc/server@10.0.0-rc.6 OK for: @trpc/client@10.0.0-rc.6 want: 10.0.0-rc.6
75 silly placeDep ROOT @trpc/next@10.0.0-rc.6 OK for: template@0.1.0 want: *
76 silly placeDep ROOT @tanstack/react-query@4.14.5 OK for: @trpc/next@10.0.0-rc.6 want: ^4.3.8
77 silly placeDep ROOT @trpc/react-query@10.0.0-rc.6 OK for: @trpc/next@10.0.0-rc.6 want: ^10.0.0-proxy-beta.21
78 timing idealTree Completed in 512ms
79 timing command:install Completed in 518ms
80 verbose stack Error: could not resolve
80 verbose stack     at PlaceDep.failPeerConflict (/Users/jacksonoppenheim/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:549:25)
80 verbose stack     at PlaceDep.place (/Users/jacksonoppenheim/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:199:21)
80 verbose stack     at new PlaceDep (/Users/jacksonoppenheim/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:73:10)
80 verbose stack     at /Users/jacksonoppenheim/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:990:31
80 verbose stack     at Array.map (<anonymous>)
80 verbose stack     at Arborist.[buildDepStep] (/Users/jacksonoppenheim/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:990:8)
80 verbose stack     at async Arborist.buildIdealTree (/Users/jacksonoppenheim/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
80 verbose stack     at async Promise.all (index 1)
80 verbose stack     at async Arborist.reify (/Users/jacksonoppenheim/.nvm/versions/node/v16.15.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
80 verbose stack     at async Install.exec (/Users/jacksonoppenheim/.nvm/versions/node/v16.15.1/lib/node_modules/npm/lib/commands/install.js:156:5)
81 verbose cwd /Users/jacksonoppenheim/projects/surreal-todo
82 verbose Darwin 20.6.0
83 verbose node v16.15.1
84 verbose npm  v8.11.0
85 error code ERESOLVE
86 error ERESOLVE could not resolve
87 error
88 error While resolving: template@0.1.0
88 error Found: @trpc/client@10.0.0-rc.6
88 error node_modules/@trpc/client
88 error   @trpc/client@"*" from the root project
88 error   peer @trpc/client@"10.0.0-rc.6" from @trpc/next@10.0.0-rc.6
88 error   node_modules/@trpc/next
88 error     @trpc/next@"*" from the root project
88 error   1 more (@trpc/react-query)
88 error
88 error Could not resolve dependency:
88 error @trpc/react@"*" from the root project
88 error
88 error Conflicting peer dependency: @trpc/client@9.27.4
88 error node_modules/@trpc/client
88 error   peer @trpc/client@"9.27.4" from @trpc/react@9.27.4
88 error   node_modules/@trpc/react
88 error     @trpc/react@"*" from the root project
88 error
88 error Fix the upstream dependency conflict, or retry
88 error this command with --force, or --legacy-peer-deps
88 error to accept an incorrect (and potentially broken) dependency resolution.
88 error
88 error See /Users/jacksonoppenheim/.npm/eresolve-report.txt for a full report.
89 verbose exit 1
90 timing npm Completed in 608ms
91 verbose unfinished npm timer reify 1667757179421
92 verbose unfinished npm timer reify:loadTrees 1667757179424
93 verbose unfinished npm timer idealTree:buildDeps 1667757179582
94 verbose unfinished npm timer idealTree:#root 1667757179582
95 verbose code 1
96 error A complete log of this run can be found in:
96 error     /Users/jacksonoppenheim/.npm/_logs/2022-11-06T17_52_59_336Z-debug-0.log

```

**Comment by nexxeln** [comment]
Can you also mention the ct3a version? It's in package.json

**Comment by AyanavaKarmakar** [comment]
- Using auto install

![auto](https://user-images.githubusercontent.com/89210438/200188516-4059c712-d6d6-4403-9736-b5205227d377.png)

- Manual install

![manual](https://user-images.githubusercontent.com/89210438/200188721-753bf78a-33fe-4fe3-9ae8-89e0f7b60240.png)

Can't reproduce. Why not use [this](https://beta.create.t3.gg/en/installation#overview) though
```shell
npx create-t3-app@latest
```

**Comment by juliusmarminge** [comment]
The error message leads me to think you're pulling a weird version (we aren't installing @trpc/react anymore - it's @trpc/react-query nowadays)

Always use @latest tag to make sure you get the latest version from the registry

**Comment by jacksonopp** [comment]
@AyanavaKarmakar @nexxeln @juliusmarminge Looks like the problem is user error. I think I was using an outdated version of ct3a, and I wasn't using `@latest`.

In summary, RTFM!!!
